<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEcv12gy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEcv12gy/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerEcv12gy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerEcv12gy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerEcv12gy\appProdProjectContainer([
    'container.build_hash' => 'Ecv12gy',
    'container.build_id' => '47cbec78',
    'container.build_time' => 1642688397,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEcv12gy');
