<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOtzm8xa\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOtzm8xa/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOtzm8xa.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOtzm8xa\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOtzm8xa\appProdProjectContainer([
    'container.build_hash' => 'Otzm8xa',
    'container.build_id' => '40854530',
    'container.build_time' => 1642680181,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOtzm8xa');
